### ISSUE TITLE
how to run this program?

### ISSUE THREAD

**Issue by LearningByGeek** [chadiik/freight-packer#1]
I'm a fresh man to learn this program, can you help me tutorial. thank you

**Comment by chadiik** [comment]
Well first start by learning what issues are:
'Issues are a great way to keep track of tasks, enhancements, and bugs for projects.'

Then about asking for help: [https://stackoverflow.com/help/how-to-ask](https://stackoverflow.com/help/how-to-ask)

But anyway, more to the point, you should look into managing javascript packages with node:
[https://stackoverflow.com/questions/2353818/how-do-i-get-started-with-node-js](https://stackoverflow.com/questions/2353818/how-do-i-get-started-with-node-js)

Then on how to serve local files: [https://stackoverflow.com/questions/tagged/webserver](https://stackoverflow.com/questions/tagged/webserver)

Good luck
